/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.model.Produto;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Pablo
 */
public class GuiProduto extends javax.swing.JFrame {

    /**
     * Creates new form GuiProduto
     */
    public GuiProduto(ArrayList <Produto> cadProd) {
        initComponents();
        cadProduto = cadProd;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSair = new javax.swing.JToggleButton();
        lblCodigo = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        lblQtdeDisponivel = new javax.swing.JLabel();
        lblPrecoUnitario = new javax.swing.JLabel();
        lblEstoqueMin = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        txtQtdeDisponivel = new javax.swing.JTextField();
        txtPrecoUnitario = new javax.swing.JTextField();
        txtEstoqueMin = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        btnIncluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Produto");

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Sair.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.setName("btnSair"); // NOI18N
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        lblCodigo.setText("Código");

        lblDescricao.setText("Descrição");

        lblQtdeDisponivel.setText("Qtde. Disponível");

        lblPrecoUnitario.setText("Preço Unitário");

        lblEstoqueMin.setText("Estoque Mínimo");

        txtDescricao.setEnabled(false);

        txtQtdeDisponivel.setEnabled(false);

        txtPrecoUnitario.setEnabled(false);

        txtEstoqueMin.setEnabled(false);

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Consultar.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Inserir.png"))); // NOI18N
        btnIncluir.setText("Incluir");
        btnIncluir.setEnabled(false);
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Remover.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescricao)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lblCodigo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnConsultar)
                                .addGap(38, 38, 38)
                                .addComponent(btnIncluir)
                                .addGap(10, 10, 10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblQtdeDisponivel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtQtdeDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblPrecoUnitario)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPrecoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(lblEstoqueMin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEstoqueMin))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnAlterar)
                                .addGap(29, 29, 29)
                                .addComponent(btnExcluir)
                                .addGap(18, 18, 18)
                                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescricao)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQtdeDisponivel)
                    .addComponent(lblPrecoUnitario)
                    .addComponent(lblEstoqueMin)
                    .addComponent(txtQtdeDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstoqueMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair)
                    .addComponent(btnConsultar)
                    .addComponent(btnIncluir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // Botao consultar:
        if (Produto.validarCodigo(txtCodigo.getText())&& 
           (!(txtCodigo.getText() == null || txtCodigo.getText().trim().isEmpty()))){
        
            int c;

            for (c=0; c < cadProduto.size(); c++ ){

                if (cadProduto.get(c).getCodigo().equals(txtCodigo.getText())){

                    break;
                }
            }

            if (c < cadProduto.size()){
                posProduto = c;
            }

            else{
                posProduto = -1;
            }

            //Encontrou
            if (posProduto >= 0){

                btnConsultar.setEnabled(false);
                btnIncluir.setEnabled(false);
                btnAlterar.setEnabled(true);
                btnExcluir.setEnabled(true);

                //Carregando atributos para editar
                txtDescricao.setText(cadProduto.get(posProduto).getDescricao());
                txtQtdeDisponivel.setText(Double.toString(cadProduto.get(posProduto).getQtdeEstoque()));
                txtPrecoUnitario.setText(Double.toString(cadProduto.get(posProduto).getPreco()));
                txtEstoqueMin.setText(Double.toString(cadProduto.get(posProduto).getEstoqueMinimo()));

            }
            //Não encontrou
            else{
                btnConsultar.setEnabled(false);
                btnIncluir.setEnabled(true);
                btnAlterar.setEnabled(false);
                btnExcluir.setEnabled(false);

            }
            //Ativando/Desativando campos para edição ou inserção
            txtCodigo.setEnabled(false);
            txtDescricao.setEnabled(true);
            txtQtdeDisponivel.setEnabled(true);
            txtPrecoUnitario.setEnabled(true);
            txtEstoqueMin.setEnabled(true);
            txtDescricao.requestFocus(); //foco no atributo nome
        }
    
    else{
        JOptionPane.showMessageDialog(null,"Favor inserir apenas numeros inteiros no campo \"codigo produto\"","Erro",JOptionPane.INFORMATION_MESSAGE);
        txtCodigo.setText(null);
        txtCodigo.requestFocus();
    }
      
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        //Criando um obj Produto
        
        //instanciando o novo objeto
        Produto objProduto = new Produto(txtCodigo.getText(), txtDescricao.getText());
        //Adicionando na coleção
        cadProduto.add(objProduto);
        //objProduto.setDescricao(txtDescricao.getText());
        objProduto.setQtdeEstoque(Double.parseDouble(txtQtdeDisponivel.getText()));
        objProduto.setPreco(Double.parseDouble(txtPrecoUnitario.getText()));
        objProduto.setEstoqueMinimo(Double.parseDouble(txtEstoqueMin.getText()));
        
        //Limpando valores dos campos
        txtCodigo.setText(null);
        txtDescricao.setText(null);
        txtQtdeDisponivel.setText(null);
        txtPrecoUnitario.setText(null);
        txtEstoqueMin.setText(null);
        
        //Ativando e desativando botões
        btnConsultar.setEnabled(true);
        btnIncluir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        txtCodigo.setEnabled(true);
        txtDescricao.setEnabled(false);
        txtQtdeDisponivel.setEnabled(false);
        txtPrecoUnitario.setEnabled(false);
        txtEstoqueMin.setEnabled(false);
        txtCodigo.requestFocus();

    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        //botao alterar
        //Pegando os valores
        cadProduto.get(posProduto).setDescricao(txtDescricao.getText());
        cadProduto.get(posProduto).setQtdeEstoque(Double.parseDouble(txtQtdeDisponivel.getText()));
        cadProduto.get(posProduto).setPreco(Double.parseDouble(txtPrecoUnitario.getText()));
        cadProduto.get(posProduto).setEstoqueMinimo(Double.parseDouble(txtEstoqueMin.getText()));

        //Liberar e fechar campos
        txtCodigo.setEnabled(true);
        txtDescricao.setEnabled(false);
        txtQtdeDisponivel.setEnabled(false);
        txtPrecoUnitario.setEnabled(false);
        txtEstoqueMin.setEnabled(false);

        //Liberar e travar botões
        btnConsultar.setEnabled(true);
        btnIncluir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        //Limpar campos
        txtCodigo.setText(null);
        txtDescricao.setText(null);
        txtQtdeDisponivel.setText(null);
        txtPrecoUnitario.setText(null);
        txtEstoqueMin.setText(null);
        txtCodigo.requestFocus();
                        
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // Botão de exclusão
        
        if (posProduto >= 0){
            cadProduto.remove(posProduto);
            posProduto--;
        }
        //Limpando os campos
        txtCodigo.setText(null);
        txtDescricao.setText(null);
        txtQtdeDisponivel.setText(null);
        txtPrecoUnitario.setText(null);
        txtEstoqueMin.setText(null);

        //Ativando e desativando campos
        txtCodigo.setEnabled(true);
        txtDescricao.setEnabled(false);
        txtQtdeDisponivel.setEnabled(false);
        txtPrecoUnitario.setEnabled(false);
        txtEstoqueMin.setEnabled(false);;

        //Ativando e desativando botoões
        btnConsultar.setEnabled(true);
        btnIncluir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        
        txtCodigo.requestFocus();
        //Codigo		
//Descricao
//QtdeDisponivel
//PrecoUnitario
//EstoqueMin
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JToggleButton btnSair;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblEstoqueMin;
    private javax.swing.JLabel lblPrecoUnitario;
    private javax.swing.JLabel lblQtdeDisponivel;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtEstoqueMin;
    private javax.swing.JTextField txtPrecoUnitario;
    private javax.swing.JTextField txtQtdeDisponivel;
    // End of variables declaration//GEN-END:variables
private ArrayList <Produto> cadProduto;
private int posProduto;
}
